apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-deploy-secret
  name: web-deploy-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deploy-secret
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-deploy-secret
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello-app
        env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: my-secret-env
              key: username
        ports:
        - containerPort: 80
        resources: {}
status: {}
